// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//协议类型
type ProtocolType int32

const (
	ProtocolType_UNKNOWN       ProtocolType = 0
	ProtocolType_CONNECT       ProtocolType = 1
	ProtocolType_CONNECTACK    ProtocolType = 2
	ProtocolType_SUB           ProtocolType = 3
	ProtocolType_SUBACK        ProtocolType = 4
	ProtocolType_UNSUB         ProtocolType = 5
	ProtocolType_UNSUBACK      ProtocolType = 6
	ProtocolType_HOLDMIC       ProtocolType = 7
	ProtocolType_HOLDMICACK    ProtocolType = 8
	ProtocolType_RELEASEMIC    ProtocolType = 9
	ProtocolType_RELEASEMICACK ProtocolType = 10
	ProtocolType_DISCONNECT    ProtocolType = 11
	ProtocolType_DISCONNECTACK ProtocolType = 12
	ProtocolType_REGISTER      ProtocolType = 13
	ProtocolType_REGISTERACK   ProtocolType = 14
	ProtocolType_SYSTEM        ProtocolType = 15
	ProtocolType_SYSTEMACK     ProtocolType = 16
)

var ProtocolType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "CONNECT",
	2:  "CONNECTACK",
	3:  "SUB",
	4:  "SUBACK",
	5:  "UNSUB",
	6:  "UNSUBACK",
	7:  "HOLDMIC",
	8:  "HOLDMICACK",
	9:  "RELEASEMIC",
	10: "RELEASEMICACK",
	11: "DISCONNECT",
	12: "DISCONNECTACK",
	13: "REGISTER",
	14: "REGISTERACK",
	15: "SYSTEM",
	16: "SYSTEMACK",
}

var ProtocolType_value = map[string]int32{
	"UNKNOWN":       0,
	"CONNECT":       1,
	"CONNECTACK":    2,
	"SUB":           3,
	"SUBACK":        4,
	"UNSUB":         5,
	"UNSUBACK":      6,
	"HOLDMIC":       7,
	"HOLDMICACK":    8,
	"RELEASEMIC":    9,
	"RELEASEMICACK": 10,
	"DISCONNECT":    11,
	"DISCONNECTACK": 12,
	"REGISTER":      13,
	"REGISTERACK":   14,
	"SYSTEM":        15,
	"SYSTEMACK":     16,
}

func (x ProtocolType) String() string {
	return proto.EnumName(ProtocolType_name, int32(x))
}

func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

type Control struct {
	ProtocolType         ProtocolType `protobuf:"varint,1,opt,name=protocolType,proto3,enum=order.ProtocolType" json:"protocolType,omitempty"`
	OrgID                uint32       `protobuf:"varint,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	UserID               uint32       `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	RootGroupID          uint32       `protobuf:"varint,4,opt,name=rootGroupID,proto3" json:"rootGroupID,omitempty"`
	GroupID              uint32       `protobuf:"varint,5,opt,name=groupID,proto3" json:"groupID,omitempty"`
	AckCode              uint32       `protobuf:"varint,6,opt,name=ackCode,proto3" json:"ackCode,omitempty"`
	SubGroup             string       `protobuf:"bytes,7,opt,name=subGroup,proto3" json:"subGroup,omitempty"`
	TopicPriority        uint32       `protobuf:"varint,8,opt,name=topicPriority,proto3" json:"topicPriority,omitempty"`
	MicPriority          uint32       `protobuf:"varint,9,opt,name=micPriority,proto3" json:"micPriority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Control) Reset()         { *m = Control{} }
func (m *Control) String() string { return proto.CompactTextString(m) }
func (*Control) ProtoMessage()    {}
func (*Control) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}
func (m *Control) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Control) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Control.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Control) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Control.Merge(m, src)
}
func (m *Control) XXX_Size() int {
	return m.Size()
}
func (m *Control) XXX_DiscardUnknown() {
	xxx_messageInfo_Control.DiscardUnknown(m)
}

var xxx_messageInfo_Control proto.InternalMessageInfo

func (m *Control) GetProtocolType() ProtocolType {
	if m != nil {
		return m.ProtocolType
	}
	return ProtocolType_UNKNOWN
}

func (m *Control) GetOrgID() uint32 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *Control) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Control) GetRootGroupID() uint32 {
	if m != nil {
		return m.RootGroupID
	}
	return 0
}

func (m *Control) GetGroupID() uint32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *Control) GetAckCode() uint32 {
	if m != nil {
		return m.AckCode
	}
	return 0
}

func (m *Control) GetSubGroup() string {
	if m != nil {
		return m.SubGroup
	}
	return ""
}

func (m *Control) GetTopicPriority() uint32 {
	if m != nil {
		return m.TopicPriority
	}
	return 0
}

func (m *Control) GetMicPriority() uint32 {
	if m != nil {
		return m.MicPriority
	}
	return 0
}

func init() {
	proto.RegisterEnum("order.ProtocolType", ProtocolType_name, ProtocolType_value)
	proto.RegisterType((*Control)(nil), "order.Control")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0x4e, 0x7d, 0x3b, 0xb6, 0xd3, 0xe1, 0x80, 0xd0, 0x88, 0x85, 0x65, 0x21, 0x16,
	0x11, 0x8b, 0x2e, 0x60, 0xc1, 0xba, 0xb1, 0xad, 0x62, 0xb5, 0x75, 0x2a, 0x5f, 0x84, 0x58, 0xd2,
	0xd4, 0xaa, 0x22, 0x0a, 0x63, 0x4d, 0x9c, 0x45, 0xd6, 0xbc, 0x04, 0xcf, 0xc0, 0x93, 0xb0, 0xe4,
	0x11, 0x50, 0x78, 0x11, 0x74, 0xc6, 0x4e, 0xe3, 0xec, 0xe6, 0xfb, 0xbf, 0x7f, 0x8e, 0x8f, 0xac,
	0x01, 0x4f, 0xaa, 0xfb, 0x46, 0x9d, 0xb7, 0x4a, 0x76, 0x12, 0x4d, 0x0d, 0xaf, 0x7f, 0x19, 0x60,
	0xc7, 0xf2, 0x7b, 0xa7, 0xe4, 0x23, 0x7e, 0x00, 0x5f, 0xbb, 0xa5, 0x7c, 0xac, 0xb6, 0x6d, 0x23,
	0x58, 0xc4, 0x66, 0xd3, 0x77, 0xcf, 0xcf, 0xfb, 0x6b, 0xb7, 0x23, 0x55, 0x1c, 0x15, 0xf1, 0x05,
	0x98, 0x52, 0x3d, 0x64, 0x89, 0x30, 0x22, 0x36, 0x0b, 0x8a, 0x1e, 0xf0, 0x25, 0x58, 0x9b, 0x75,
	0xa3, 0xb2, 0x44, 0x4c, 0x74, 0x3c, 0x10, 0x46, 0xe0, 0x29, 0x29, 0xbb, 0x4b, 0x25, 0x37, 0x6d,
	0x96, 0x88, 0x53, 0x2d, 0xc7, 0x11, 0x0a, 0xb0, 0x1f, 0x06, 0x6b, 0x6a, 0xbb, 0x47, 0x32, 0x5f,
	0x96, 0x5f, 0x63, 0x79, 0xdf, 0x08, 0xab, 0x37, 0x03, 0xe2, 0x2b, 0x70, 0xd6, 0x9b, 0x3b, 0x3d,
	0x41, 0xd8, 0x11, 0x9b, 0xb9, 0xc5, 0x13, 0xe3, 0x1b, 0x08, 0x3a, 0xd9, 0xae, 0x96, 0xb7, 0x6a,
	0x25, 0xd5, 0xaa, 0xdb, 0x0a, 0x47, 0xdf, 0x3d, 0x0e, 0x69, 0xaf, 0x6f, 0xa3, 0x8e, 0xdb, 0xef,
	0x35, 0x8a, 0xde, 0xfe, 0x30, 0xc0, 0x1f, 0xff, 0x06, 0xf4, 0xc0, 0xae, 0xf3, 0xab, 0x7c, 0xf1,
	0x29, 0xe7, 0x27, 0x04, 0xf1, 0x22, 0xcf, 0xd3, 0xb8, 0xe2, 0x0c, 0xa7, 0x00, 0x03, 0x5c, 0xc4,
	0x57, 0xdc, 0x40, 0x1b, 0x26, 0x65, 0x3d, 0xe7, 0x13, 0x04, 0xb0, 0xca, 0x7a, 0x4e, 0xe1, 0x29,
	0xba, 0x60, 0xd6, 0x39, 0xc5, 0x26, 0xfa, 0xe0, 0xe8, 0x23, 0x09, 0x8b, 0x46, 0x7d, 0x5c, 0x5c,
	0x27, 0x37, 0x59, 0xcc, 0x6d, 0x1a, 0x35, 0x00, 0x49, 0x87, 0xb8, 0x48, 0xaf, 0xd3, 0x8b, 0x32,
	0x25, 0xef, 0xe2, 0x33, 0x08, 0x0e, 0x4c, 0x15, 0xa0, 0x4a, 0x92, 0x95, 0xfb, 0x6d, 0x3c, 0xaa,
	0x1c, 0x98, 0x2a, 0x3e, 0x7d, 0xb0, 0x48, 0x2f, 0xb3, 0xb2, 0x4a, 0x0b, 0x1e, 0xe0, 0x19, 0x78,
	0x7b, 0x22, 0x3d, 0xd5, 0x6b, 0x7e, 0x2e, 0xab, 0xf4, 0x86, 0x9f, 0x61, 0x00, 0x6e, 0x7f, 0x26,
	0xc5, 0xe7, 0xfc, 0xf7, 0x2e, 0x64, 0x7f, 0x76, 0x21, 0xfb, 0xbb, 0x0b, 0xd9, 0xcf, 0x7f, 0xe1,
	0xc9, 0x9d, 0xa5, 0x5f, 0xc3, 0xfb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0xef, 0xf2, 0xe5,
	0x61, 0x02, 0x00, 0x00,
}

func (m *Control) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Control) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ProtocolType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.ProtocolType))
	}
	if m.OrgID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.OrgID))
	}
	if m.UserID != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.UserID))
	}
	if m.RootGroupID != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.RootGroupID))
	}
	if m.GroupID != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.GroupID))
	}
	if m.AckCode != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.AckCode))
	}
	if len(m.SubGroup) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintOrder(dAtA, i, uint64(len(m.SubGroup)))
		i += copy(dAtA[i:], m.SubGroup)
	}
	if m.TopicPriority != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.TopicPriority))
	}
	if m.MicPriority != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintOrder(dAtA, i, uint64(m.MicPriority))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintOrder(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Control) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProtocolType != 0 {
		n += 1 + sovOrder(uint64(m.ProtocolType))
	}
	if m.OrgID != 0 {
		n += 1 + sovOrder(uint64(m.OrgID))
	}
	if m.UserID != 0 {
		n += 1 + sovOrder(uint64(m.UserID))
	}
	if m.RootGroupID != 0 {
		n += 1 + sovOrder(uint64(m.RootGroupID))
	}
	if m.GroupID != 0 {
		n += 1 + sovOrder(uint64(m.GroupID))
	}
	if m.AckCode != 0 {
		n += 1 + sovOrder(uint64(m.AckCode))
	}
	l = len(m.SubGroup)
	if l > 0 {
		n += 1 + l + sovOrder(uint64(l))
	}
	if m.TopicPriority != 0 {
		n += 1 + sovOrder(uint64(m.TopicPriority))
	}
	if m.MicPriority != 0 {
		n += 1 + sovOrder(uint64(m.MicPriority))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovOrder(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOrder(x uint64) (n int) {
	return sovOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Control) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Control: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Control: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolType", wireType)
			}
			m.ProtocolType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolType |= (ProtocolType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgID", wireType)
			}
			m.OrgID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrgID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			m.UserID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootGroupID", wireType)
			}
			m.RootGroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RootGroupID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			m.GroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckCode", wireType)
			}
			m.AckCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AckCode |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubGroup", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubGroup = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicPriority", wireType)
			}
			m.TopicPriority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicPriority |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MicPriority", wireType)
			}
			m.MicPriority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MicPriority |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthOrder
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOrder
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOrder(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOrder = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrder   = fmt.Errorf("proto: integer overflow")
)
